trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 0 * * *"
    displayName: "Daily Player Data Update by Country"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      docker-compose up --build -d
    displayName: "Build and run Docker Compose"
